FROM docker.io/triliumnext/trilium:v0.104.1

ARG BUILD_VERSION
ARG BUILD_ARCH

LABEL \
    io.hass.name="Trilium Notes" \
    io.hass.description="Hierarchical note-taking application" \
    io.hass.version="${BUILD_VERSION}" \
    io.hass.type="addon" \
    io.hass.arch="${BUILD_ARCH}" \
    org.opencontainers.image.source="https://github.com/HyperCriSiS/Home-Assistant-Addons" \
    org.opencontainers.image.version="${BUILD_VERSION}"
